Dazzle.constant.UtilsEnums = {
	//日期格式
	DATE_FORMAT_TYPE_0 : "yyyyMMdd",
	DATE_FORMAT_TYPE_1 : "yyyy-MM-dd",
	DATE_FORMAT_TYPE_2 : "HHmmss",
	DATE_FORMAT_TYPE_3 : "HH:mm:ss",
	DATE_FORMAT_TYPE_4 : "HHmmssSSS",
	DATE_FORMAT_TYPE_5 : "HH:mm:ss.SSS",
	DATE_FORMAT_TYPE_6 : "yyyyMMddHHmmss",
	DATE_FORMAT_TYPE_7 : "yyyy-MM-dd HH:mm:ss",
	DATE_FORMAT_TYPE_8 : "yyyyMMddHHmmssSSS",
	DATE_FORMAT_TYPE_9 : "yyyy-MM-dd HH:mm:ss.SSS",
	//月全名
	MONTH_FULL_NAME_0 : "January",
	MONTH_FULL_NAME_1 : "February",
	MONTH_FULL_NAME_2 : "March",
	MONTH_FULL_NAME_3 : "April",
	MONTH_FULL_NAME_4 : "May",
	MONTH_FULL_NAME_5 : "June",
	MONTH_FULL_NAME_6 : "July",
	MONTH_FULL_NAME_7 : "August",
	MONTH_FULL_NAME_8 : "September",
	MONTH_FULL_NAME_9 : "October",
	MONTH_FULL_NAME_10 : "November",
	MONTH_FULL_NAME_11 : "December",
	//月简写名
	MONTH_SHORT_NAME_0 :"Jan",
	MONTH_SHORT_NAME_1 :"Feb",
	MONTH_SHORT_NAME_2 :"Mar",
	MONTH_SHORT_NAME_3 :"Apr",
	MONTH_SHORT_NAME_4 :"May",
	MONTH_SHORT_NAME_5 :"Jun",
	MONTH_SHORT_NAME_6 :"Jul",
	MONTH_SHORT_NAME_7 :"Aug",
	MONTH_SHORT_NAME_8 :"Sep",
	MONTH_SHORT_NAME_9 :"Oct",
	MONTH_SHORT_NAME_10 :"Nov",
	MONTH_SHORT_NAME_11 :"Dec",
	//取整类型
	ROUND_TYPE_0:"ceil",
	ROUND_TYPE_1:"round",
	ROUND_TYPE_2:"floor"
}
